const os = require("os")
// console.log(os.arch())
// console.log(`${os.freemem()/1024/1024/1024}`)
// console.log(os.cpus())
// console.log(os.getPriority())
// console.log(os.homedir())
// console.log(os.hostname())
// console.log(os.loadavg())
// console.log(os.networkInterfaces())
// console.log(os.version())
// console.log(os.userInfo())
// console.log(`${os.uptime()/60/60}`)
// console.log(os.type())
// console.log(os.totalmem())
// console.log(os.tmpdir())
// console.log(os.setPriority(1))
// console.log(os.release())
// console.log(os.platform())

